# Generated by Django 3.2.9 on 2021-11-05 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('number', models.CharField(help_text='Укажите номер объекта ИС', max_length=15, verbose_name='Номер объекта ИС')),
                ('title', models.CharField(blank=True, help_text='Напишите название объекта ИС', max_length=200, verbose_name='Название объекта ИС')),
                ('description', models.TextField(blank=True, help_text='Описание объекта ИС', max_length=300, verbose_name='Опишите объект ИС')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
