# Generated by Django 3.2.9 on 2021-11-05 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='initial_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
