# Generated by Django 3.2.9 on 2021-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipitem', '0002_item_initial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type_of_item',
            field=models.CharField(choices=[('PM', 'полезная модель'), ('IZ', 'изобретение'), ('PO', 'промышленный образец'), ('TM', 'товарный знак')], default='PM', max_length=2),
        ),
    ]
