# Generated by Django 3.2.9 on 2021-11-05 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211105_2046'),
        ('ipitem', '0003_item_type_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='initial_date',
            field=models.DateField(default=datetime.date.today, help_text='Укажите дату', verbose_name='Дата начала действия'),
        ),
    ]
