# Generated by Django 3.2.9 on 2021-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipitem', '0004_auto_20211105_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_of_item',
            field=models.CharField(choices=[('PM', 'полезная модель'), ('IZ', 'изобретение'), ('PO', 'промышленный образец'), ('TM', 'товарный знак')], default='PM', max_length=2, verbose_name='Тип объекта ИС'),
        ),
    ]
