# Generated by Django 3.2.9 on 2021-11-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_email'),
        ('ipitem', '0006_alter_item_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='IpItem',
        ),
    ]
