# Generated by Django 3.2.9 on 2021-11-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipitem', '0007_rename_item_ipitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipitem',
            name='signatory',
            field=models.CharField(default='', help_text='В формате ФИО или Директор ООО "Рога и копыта" ФИО', max_length=15, verbose_name='Подписант'),
        ),
    ]
