# Generated by Django 3.2.9 on 2021-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipitem', '0008_ipitem_signatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipitem',
            name='type_of_item',
            field=models.CharField(choices=[('PM', 'полезная модель'), ('IZ', 'изобретение'), ('PO', 'промышленный образец')], default='PM', max_length=2, verbose_name='Тип объекта ИС'),
        ),
    ]
