# Generated by Django 3.2.9 on 2021-11-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
